### ISSUE TITLE
Failed with docker-compose sandbox

### ISSUE THREAD

**Issue by gernotstarke** [tinkerbell/sandbox#167]
I want to provision a few bare-metal HP desktop machines with tinkerbell.

## Expected Behaviour
I follow the steps in the docker-compose sandbox, and will afterwards have a machine with a provisioned OS (Ubuntu) on it.

https://github.com/tinkerbell/sandbox/blob/main/docs/quickstarts/COMPOSE.md

## Current Behaviour
All containers are started, exactly as in the COMPOSE.md expected-output-step-4.

After that, **nothing** happens.

## Possible Solution
* please describe some ideas how to debug or where to look for potential configuration errors.
* I have a few years of sw-development experience, basic networking knowledge, now my way around Docker.
Even with this background, I saw no chance to get any further. Although Tinkerbell really looks nice from a birds' eye perspective, 
## Steps to Reproduce (for bugs)

In the hardware.yaml, certain values remain unexplained:

1. `$TINKERBELL_CLIENT_GW`: is this the gateway to the "outer" network?
2. How shall I know the TINKERBELL_CLIENT_IP, the (Tink-) DHCP-server is supposed to create one for that machine...
3. metadata, facility?
4. Can I modify the hardware.yaml while the Tink-containers are running? How do I add a second machine?

All in all, the documentation left too many questions open for me. Sorry to say that.

## Context
I wanted to try out the most basic step, install Ubuntu on a bare metal machine. Failed.

## Your Environment
docker-compose running on MacOS (the provisioner). 

5-port switch connected over USB to the provisioner. Provisioner connected over a second ethernet to DSL router/internet.

HP-EliteDesk mini PCs connected to the switch. Boot-order (in BIOS) set to 1.Netboot, 2.USB, 3. SSD

DHCP-scan on HP starts, but Tinkerbell does not provide an IP adress to the client.

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

```
apiVersion: "tinkerbell.org/v1alpha1"
kind: Hardware
metadata:
  name: machine1
spec:
  disks:
    - device: $DISK_DEVICE
  metadata:
    facility:
      facility_code: sandbox
    instance:
      hostname: "machine1"
      id: "$TINKERBELL_CLIENT_MAC"
      operating_system:
        distro: "ubuntu"
        os_slug: "ubuntu_20_04"
        version: "20.04"
  interfaces:
    - dhcp:
        arch: x86_64
        hostname: machine1
        ip:
          address: 192.168.178.230
          gateway: $TINKERBELL_CLIENT_GW
          netmask: 255.255.255.0
        lease_time: 86400
#        mac: "FC:3F:DB:05:70:CD"
        mac: "EC:8E:B5:77:9E:2D"
        name_servers: [],
        uefi: false
      netboot:
        allowPXE: true
        allowWorkflow: true
```
